# Generated by Django 4.1.7 on 2023-06-20 08:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('Loan_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.TextField(blank=True, null=True)),
                ('Surname', models.TextField(blank=True, null=True)),
                ('Duration', models.IntegerField()),
                ('LandBoard', models.TextField(blank=True, null=True)),
                ('Principal', models.IntegerField()),
                ('Start', models.CharField(blank=True, max_length=15, null=True)),
                ('End', models.CharField(blank=True, max_length=15, null=True)),
                ('Form', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('ID_no', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.TextField(blank=True, null=True)),
                ('Surname', models.TextField(blank=True, null=True)),
                ('LandBoard', models.TextField(blank=True, null=True)),
                ('Contact', models.IntegerField()),
                ('Residential_Address', models.CharField(blank=True, max_length=15, null=True)),
                ('Form', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('ID_Num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Name', models.TextField(blank=True, null=True)),
                ('Surname', models.TextField(blank=True, null=True)),
                ('Contact', models.IntegerField()),
                ('Voucher', models.CharField(blank=True, max_length=20, null=True)),
                ('Cell_Amount', models.CharField(blank=True, max_length=8, null=True)),
                ('Offer', models.CharField(blank=True, max_length=8, null=True)),
                ('Voucher_Start', models.CharField(blank=True, max_length=20, null=True)),
                ('Voucher_End', models.CharField(blank=True, max_length=20, null=True)),
                ('Land_Board', models.TextField(default='NULL', max_length=30)),
                ('Form', models.FileField(blank=True, null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveReques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('requested_days', models.PositiveIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
