# Generated by Django 4.1.7 on 2023-06-09 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('Message', models.TextField(blank=True, null=True)),
                ('Approval', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Voucher_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Paid_To', models.CharField(max_length=30)),
                ('Prepared_By', models.TextField(blank=True, null=True)),
                ('Funds_use_breakdown', models.TextField(blank=True, null=True)),
                ('Amount_in_words', models.TextField(blank=True, null=True)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=20, null=True)),
                ('Date', models.CharField(max_length=10)),
                ('Forms', models.FileField(blank=True, default='NULL', null=True, upload_to='pdfs/')),
            ],
        ),
        migrations.CreateModel(
            name='Petty',
            fields=[
                ('Petty_ID', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Date', models.CharField(blank=True, max_length=15, null=True)),
                ('Receipt', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('Cash_Used_For', models.TextField(blank=True, null=True)),
                ('Total_Price', models.CharField(blank=True, max_length=15, null=True)),
                ('Petty_Cash_Taken', models.CharField(blank=True, max_length=15, null=True)),
                ('Petty_Cash_Used', models.CharField(blank=True, max_length=15, null=True)),
                ('Balance', models.CharField(blank=True, max_length=15, null=True)),
                ('Balance_cd', models.CharField(blank=True, max_length=15, null=True)),
                ('Filled_In_By', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_request_id', models.IntegerField(default=1)),
                ('confirmation_status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('requested_days', models.PositiveIntegerField(default=0)),
                ('available_leave_days', models.IntegerField(default=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], default='P', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('Name', models.TextField(blank=True, null=True)),
                ('Surname', models.TextField(blank=True, null=True)),
                ('leavedays_requested', models.IntegerField()),
                ('available_leave_days', models.PositiveIntegerField(default=30)),
                ('user', models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
