# Generated by Django 4.1.7 on 2023-06-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_payment_approval_signature_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='PVNumber',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
