# Generated by Django 4.1.7 on 2023-06-21 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_alter_payment_pvnumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Forms',
            new_name='Attachments',
        ),
    ]
