# Generated by Django 4.1.7 on 2023-06-21 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0005_rename_forms_payment_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='Comments',
            field=models.CharField(default='-None', max_length=10),
        ),
    ]
