# Generated by Django 4.1.7 on 2023-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0006_payment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='petty',
            name='Approval_Signature_1',
            field=models.FileField(blank=True, default='NULL', null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='petty',
            name='Approval_Signature_2',
            field=models.FileField(blank=True, default='NULL', null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='petty',
            name='Comments',
            field=models.CharField(default='-None', max_length=10),
        ),
    ]
