# Generated by Django 4.1.7 on 2023-06-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0007_petty_approval_signature_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Approval_Signature_1',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Approval_Signature_2',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Attachments',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Comments',
            field=models.CharField(default='-None', max_length=100),
        ),
        migrations.AlterField(
            model_name='petty',
            name='Approval_Signature_1',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='petty',
            name='Approval_Signature_2',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='petty',
            name='Comments',
            field=models.CharField(max_length=10),
        ),
    ]
