# Generated by Django 4.1.7 on 2023-06-23 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0008_alter_payment_approval_signature_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='confirmation_status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1),
        ),
        migrations.AlterField(
            model_name='petty',
            name='Comments',
            field=models.CharField(max_length=100),
        ),
    ]
