# Generated by Django 4.1.7 on 2023-06-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0009_alter_leaverequest_confirmation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='confirmation_status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='status',
            field=models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected')], max_length=1),
        ),
    ]
