# Generated by Django 4.1.7 on 2023-06-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0010_alter_leaverequest_confirmation_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='Approval_Signature_1',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Approval_Signature_2',
            field=models.FileField(blank=True, upload_to='pdfs/'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='Comments',
            field=models.CharField(max_length=100),
        ),
    ]
